name: buildsln

on:
  push:
    branches:
    - '*'

jobs:
  buildsln:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - run: dotnet restore --locked-mode --force-evaluate
      - run: dotnet build DotNetty.sln
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: "**/packages.lock.json'"


