name: buildsln

on:
  push:
    branches:
    - '*'

jobs:
  buildsln:
    runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-dotnet@v4
  with:
    dotnet-version: '6.0.x'
    dotnet-quality: 'preview'
- run: dotnet build DotNetty.sln
